### ISSUE TITLE
"Requires" anomaly

### ISSUE THREAD

**Issue by vaughany** [drlikm/moodle-format_etask#2]
Hi there. This plugin, in `version.php`, 'requires' version 2014110400 of Moodle, however according to https://docs.moodle.org/dev/Releases there is no released Moodle version with this version number. 

It seems to be the last beta or release candidate of Moodle 2.8 ('2014111000')?

**Comment by drlikm** [comment]
Hi Paul, I fix this issue, thank for your report :+1:
